### ISSUE TITLE
 How to get Apex Legends dump ?

### ISSUE THREAD

**Issue by 04255** [louis-dnb/ApexLegends#1]
I am a novice, the data is very useful for me, I hope to give a tutorial to teach me how to get these key data information, in order to deal with the game update

**Comment by CodeByLM** [comment]
I will look into making a guide on Unknowncheats when i have more time.
I'll keep you updated when i release the guide.

**Comment by CodeByLM** [comment]
I made a guide on how to dump offsets on unknowncheats: https://www.unknowncheats.me/forum/apex-legends/452956-noob-friendly-guide-getting-offsets-casualx-apexbot-dumper.html#post3137326

**Comment by 04255** [comment]
Great. Thank you！You are a kind person
